# Retrieve checkout session
GET http://localhost:3000/api/checkout/session/cs_test_b1GnSP2lxLVaK0w53eDc56mJ1w8UkFSzwmLsdc5xw3Br9P5jJEi47ThgWY

###
# Create checkout session with promotion
POST http://localhost:3000/api/checkout/session/create
Content-Type: application/json

{
  "line_items": [
    {
      "price": "price_1P4LvDRx5o9wSZXBr8uODDSC",
      "quantity": 2
    }
  ],
  "allow_promotion_codes":true
}

###
# Create checkout session with coupon
POST http://localhost:3000/api/checkout/session/create
Content-Type: application/json

{
  "line_items": [
    {
      "price": "price_1P4LvDRx5o9wSZXBr8uODDSC",
      "quantity": 2
    }
  ],
  "discounts":[{"coupon":"lwV8u0HR"}]
}
