# List all products
GET http://localhost:3000/api/products/

###
# Get one product
GET http://localhost:3000/api/products/prod_Pqk0hiP7dP0YOI

###
# Get discount from promo code
GET http://localhost:3000/api/products/promotions/check/MVGINCOMING

###
# Get discount from promo code that doesn't exist
GET http://localhost:3000/api/products/promotions/check/AJABAJA
